const { exec, spawn } = require("child_process");
const util = require("util");
const execAsync = util.promisify(exec);
const fs = require("fs");
const path = require("path");
const os = require("os");

// Standalone copy of server/services/pm2Service.js adapted for the agent:
// identical behavior, but dump-corruption alerts go to the console instead of
// the panel's notification feed (the panel sees node health via /health).

const runPM2 = async (args) => {
    const { stdout, stderr } = await execAsync(
        `env -u PORT pm2 ${args} --no-color`,
    );
    return stdout || stderr;
};

// ── dump.pm2 integrity guard ─────────────────────────────────────────────────
// `pm2 save` can write a truncated or empty dump.pm2 without reporting an
// error when the disk is full. On the next reboot PM2 fails to parse that
// file, DELETES it, and comes up with an empty process list — every bot is
// gone. Every save is validated; a known-good copy is restored when corrupt.

const PM2_HOME = process.env.PM2_HOME || path.join(os.homedir(), ".pm2");
const DUMP_PATH = path.join(PM2_HOME, "dump.pm2");
const GOOD_DUMP_PATH = path.join(PM2_HOME, "dump.pm2.panel-good");

const isDumpValid = (file) => {
    try {
        const raw = fs.readFileSync(file, "utf8");
        return Array.isArray(JSON.parse(raw));
    } catch {
        return false;
    }
};

const pm2Save = async () => {
    let saveError = null;
    try {
        await execAsync("pm2 save --no-color");
    } catch (err) {
        saveError = err;
    }

    if (!saveError && isDumpValid(DUMP_PATH)) {
        try {
            fs.copyFileSync(DUMP_PATH, GOOD_DUMP_PATH);
        } catch (err) {
            console.warn("[PM2] Could not refresh known-good dump copy:", err.message);
        }
        return;
    }

    const reason = saveError ? saveError.message.split("\n")[0] : "dump.pm2 is empty or unparseable";
    console.error(`[PM2] pm2 save produced a corrupt dump (${reason})`);

    if (isDumpValid(GOOD_DUMP_PATH)) {
        try {
            fs.copyFileSync(GOOD_DUMP_PATH, DUMP_PATH);
            console.error("[PM2] Restored last known-good dump.pm2 — process list may be slightly stale");
        } catch (err) {
            console.error("[PM2] Could not restore known-good dump:", err.message);
        }
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Process Control
// ─────────────────────────────────────────────────────────────────────────────

const writeProxyConfig = (botPath, proxyConf) => {
    const { type = "socks5", host, port, username, password } = proxyConf;
    const authLine =
        username && password ? `\n${type} ${host} ${port} ${username} ${password}` : `\n${type} ${host} ${port}`;
    const content = `# Generated by bot-panel — do not edit manually
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]${authLine}
`;
    const confPath = path.join(botPath, ".proxychains4.conf");
    fs.writeFileSync(confPath, content, "utf8");
    return confPath;
};

const startBot = async (
    pm2Name,
    botPath,
    startCommand = "npm start",
    maxMemory = null,
    proxyConf = null,
) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";

    const list = await getProcessList();
    const existing = list.find((p) => p.name === pm2Name);
    if (existing) {
        // Already registered — delete and re-register so wrapper script is refreshed
        await runPM2(`delete "${pm2Name}"`);
    }

    // Resolve single-file scripts to their explicit runtime — a shell wrapper
    // cannot exec a bare .js file the way PM2 can.
    let effectiveCmd = startCommand.trim();

    const isBareFile = (cmd) =>
        !cmd.includes(" ") &&
        (cmd.endsWith(".js") || cmd.endsWith(".ts") || cmd.endsWith(".py") || cmd.endsWith(".json"));

    if (isBareFile(effectiveCmd)) {
        if (effectiveCmd.endsWith(".js")) {
            effectiveCmd = `node ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".ts")) {
            effectiveCmd = `npx ts-node ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".py")) {
            effectiveCmd = `python3 ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".json")) {
            effectiveCmd = `pm2 start ${effectiveCmd}`;
        }
        console.log(`[PM2] Resolved bare file to: ${effectiveCmd}`);
    }

    if (proxyConf) {
        const confPath = writeProxyConfig(botPath, proxyConf);
        effectiveCmd = `proxychains4 -f "${confPath}" ${effectiveCmd}`;
        console.log(`[PM2] Proxy enabled for "${pm2Name}" via ${proxyConf.host}:${proxyConf.port}`);
    }

    // Always run via wrapper script so the shell resolves the command
    const scriptPath = `${botPath}/.noflex-start.sh`;
    const NL = "\n";
    // exec only works for simple commands — shell operators require bash to run the full line
    const hasShellOps = /[;&|]/.test(effectiveCmd);
    const scriptContent = `#!/bin/bash${NL}${hasShellOps ? effectiveCmd : `exec ${effectiveCmd}`}`;
    fs.writeFileSync(scriptPath, scriptContent, "utf8");
    try { fs.chmodSync(scriptPath, 0o755); } catch (e) {}

    console.log(`[PM2] Wrapper script for "${pm2Name}": ${scriptPath}`);
    console.log(`[PM2] Effective command: ${effectiveCmd}`);

    const result = await runPM2(
        `start "${scriptPath}" --name "${pm2Name}" --cwd "${botPath}"${memFlag} --interpreter bash`,
    );

    await pm2Save();
    return result;
};

const setMemoryLimit = async (pm2Name, maxMemory) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";
    const result = await runPM2(`restart "${pm2Name}"${memFlag}`);
    await pm2Save();
    return result;
};

const startHttpServer = async (pm2Name, distFolder, port) => {
    const list = await getProcessList();
    const existing = list.find((p) => p.name === pm2Name);
    if (existing) {
        await runPM2(`delete "${pm2Name}"`);
    }

    // Prefer the binary shipped with the agent; fall back to global
    const localBin = path.resolve(__dirname, "../node_modules/.bin/http-server");
    const bin = fs.existsSync(localBin) ? localBin : "http-server";

    const scriptPath = `/tmp/panel-site-${pm2Name}.sh`;
    fs.writeFileSync(
        scriptPath,
        `#!/bin/bash\nexec "${bin}" "${distFolder}" -p ${port} -a 0.0.0.0 --silent\n`,
        "utf8",
    );
    fs.chmodSync(scriptPath, 0o755);

    const result = await runPM2(
        `start "${scriptPath}" --name "${pm2Name}" --interpreter bash`,
    );
    await pm2Save();
    return result;
};

const stopBot = async (pm2Name) => {
    const result = await runPM2(`stop "${pm2Name}"`);
    await pm2Save();
    return result;
};

const restartBot = async (pm2Name) => {
    const result = await runPM2(`restart "${pm2Name}"`);
    await pm2Save();
    return result;
};

const deleteBot = async (pm2Name) => {
    try {
        const result = await runPM2(`delete "${pm2Name}"`);
        await pm2Save();
        return result;
    } catch {
        // Process doesn't exist in PM2 — that's fine
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Status & Logs
// ─────────────────────────────────────────────────────────────────────────────

const getProcessList = async () => {
    try {
        const { stdout } = await execAsync("pm2 jlist --no-color");
        return JSON.parse(stdout || "[]");
    } catch {
        return [];
    }
};

const getBotStatus = async (pm2Name, cachedList = null) => {
    const list = cachedList || (await getProcessList());
    const proc = list.find((p) => p.name === pm2Name);

    if (!proc)
        return { status: "stopped", cpu: 0, memory: 0, restarts: 0, uptime: null };

    return {
        status: proc.pm2_env.status,
        cpu: proc.monit?.cpu ?? 0,
        memory: proc.monit?.memory ?? 0,
        restarts: proc.pm2_env.restart_time ?? 0,
        uptime: proc.pm2_env.pm_uptime ?? null,
    };
};

const getBotLogs = async (pm2Name, lines = 100) => {
    try {
        const { stdout } = await execAsync(
            `pm2 logs "${pm2Name}" --lines ${lines} --nostream --no-color`,
        );
        return stdout;
    } catch (err) {
        return err.message;
    }
};

const streamBotLogs = (pm2Name, lines = 50) => {
    return spawn(
        "pm2",
        ["logs", pm2Name, "--lines", String(lines), "--raw", "--no-color"],
        { stdio: ["ignore", "pipe", "pipe"] },
    );
};

const flushBotLogs = async (pm2Name) => {
    await execAsync(`pm2 flush "${pm2Name}"`);
};

module.exports = {
    startBot,
    startHttpServer,
    stopBot,
    restartBot,
    deleteBot,
    setMemoryLimit,
    getBotStatus,
    getBotLogs,
    streamBotLogs,
    getProcessList,
    flushBotLogs,
};
