const { exec } = require("child_process");
const { promisify } = require("util");
const fs = require("fs");
const path = require("path");
const os = require("os");

/**
 * wg.js — WireGuard control on the agent, driven by the panel (the coordinator).
 * The agent owns its private key (never leaves the box); the panel only ever sees
 * the public key. The panel assigns the overlay IP and pushes the full peer list;
 * the agent writes /etc/wireguard/wg0.conf and brings up / live-reloads the tunnel.
 *
 * Safety: peers use narrow AllowedIPs (each peer's /32 only) — the tunnel never
 * becomes a default route, so SSH / normal traffic are untouched.
 */

const run = promisify(exec);

const IFACE = "wg0";
const WG_DIR = "/etc/wireguard";
const CONF_PATH = `${WG_DIR}/${IFACE}.conf`;
// Agent-owned key store (does not need root; only the conf write / interface up do).
const KEY_DIR = path.join(__dirname, "..", ".wg");
const PRIV_PATH = path.join(KEY_DIR, "privatekey");
const PUB_PATH = path.join(KEY_DIR, "publickey");
const DEFAULT_PORT = parseInt(process.env.WG_PORT || "51820", 10) || 51820;

// Root runs wg directly; a non-root agent must have passwordless sudo for wg/wg-quick.
const SUDO = typeof process.getuid === "function" && process.getuid() === 0 ? "" : "sudo -n ";

async function _sh(cmd) {
    const { stdout } = await run(cmd, { timeout: 20000 });
    return stdout.trim();
}

/** Generate the keypair once (idempotent). Returns the public key. */
async function ensureKeypair() {
    if (!fs.existsSync(KEY_DIR)) fs.mkdirSync(KEY_DIR, { recursive: true, mode: 0o700 });
    if (!fs.existsSync(PRIV_PATH)) {
        const priv = await _sh("wg genkey");
        fs.writeFileSync(PRIV_PATH, priv + "\n", { mode: 0o600 });
        const pub = await _sh(`printf %s "${priv}" | wg pubkey`);
        fs.writeFileSync(PUB_PATH, pub + "\n", { mode: 0o644 });
    }
    return fs.readFileSync(PUB_PATH, "utf8").trim();
}

/** Public identity for the panel to register: { pubKey, listenPort }. */
async function getIdentity() {
    const pubKey = await ensureKeypair();
    return { pubKey, listenPort: DEFAULT_PORT };
}

function _buildConf({ address, listenPort }, peers) {
    const priv = fs.readFileSync(PRIV_PATH, "utf8").trim();
    const lines = [
        "# Generated by bot-panel — do not edit manually",
        "[Interface]",
        `Address = ${address}`,
        `ListenPort = ${listenPort || DEFAULT_PORT}`,
        `PrivateKey = ${priv}`,
    ];
    for (const p of peers || []) {
        if (!p.pubKey || !p.allowedIps) continue;
        lines.push("", "[Peer]", `PublicKey = ${p.pubKey}`, `AllowedIPs = ${p.allowedIps}`);
        if (p.endpoint) lines.push(`Endpoint = ${p.endpoint}`);
        lines.push(`PersistentKeepalive = ${p.keepalive || 25}`);
    }
    return lines.join("\n") + "\n";
}

async function _isUp() {
    try {
        await _sh(`${SUDO}wg show ${IFACE}`);
        return true;
    } catch {
        return false;
    }
}

/**
 * Apply the mesh: write the conf and bring up (or live-reload) the interface.
 * @param {{address:string, listenPort?:number}} iface
 * @param {Array<{pubKey,allowedIps,endpoint?,keepalive?}>} peers
 */
async function applyConfig(iface, peers) {
    await ensureKeypair();
    if (!iface?.address) throw new Error("wg: missing overlay address");
    const conf = _buildConf(iface, peers);

    // Write the conf into /etc/wireguard (root-owned) via a temp file + sudo move.
    const tmp = path.join(os.tmpdir(), `wg0.${Date.now()}.conf`);
    fs.writeFileSync(tmp, conf, { mode: 0o600 });
    await _sh(`${SUDO}mkdir -p ${WG_DIR}`);
    await _sh(`${SUDO}cp "${tmp}" "${CONF_PATH}" && ${SUDO}chmod 600 "${CONF_PATH}"`);
    fs.unlinkSync(tmp);

    // Open the UDP port (best-effort; ignore if ufw inactive).
    await _sh(`${SUDO}ufw allow ${iface.listenPort || DEFAULT_PORT}/udp`).catch(() => {});

    if (await _isUp()) {
        // Live-reload peers without tearing the interface down (keeps sessions alive).
        await _sh(`${SUDO}bash -c 'wg syncconf ${IFACE} <(wg-quick strip ${IFACE})'`);
    } else {
        await _sh(`${SUDO}wg-quick up ${IFACE}`);
    }
    return { ok: true };
}

/** Parse `wg show` into a small status object. */
async function status() {
    if (!(await _isUp())) return { up: false, peers: [] };
    const out = await _sh(`${SUDO}wg show ${IFACE} dump`);
    const rows = out.split("\n").filter(Boolean);
    // First line = interface; rest = peers: pubkey, psk, endpoint, allowedips, latest-handshake, rx, tx, keepalive
    const peers = rows.slice(1).map((r) => {
        const c = r.split("\t");
        return { pubKey: c[0], endpoint: c[2], allowedIps: c[3], latestHandshake: Number(c[4]) || 0 };
    });
    return { up: true, peers };
}

module.exports = { getIdentity, applyConfig, status, ensureKeypair };
