const crypto = require("crypto");

// ─────────────────────────────────────────────────────────────────────────────
//  application.yml renderer.
//
//  The panel owns the WHOLE file: one shared config, rendered here, pushed to
//  every node. That is what makes "edit once on the panel" true — a node whose
//  file differs is drift, and the page says so.
//
//  Rendering must be DETERMINISTIC: the same settings must produce the same
//  bytes every time. The panel compares sha256(rendered) against the sha each
//  agent reports to decide who is out of sync, so a timestamp or a Map
//  iteration order in here would make every node look permanently drifted and
//  restart them on every sync.
// ─────────────────────────────────────────────────────────────────────────────

const HEADER = `# Generated by bot-panel — do not edit on the node.
# Every change here is overwritten on the next sync from the panel's
# Lavalink page. Use the "Custom application.yml" box there to hand-write it.`;

/** Double-quoted YAML scalar, safe for passwords with quotes or backslashes. */
const q = (v) => `"${String(v ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

// Fixed order — see the determinism note above.
const SOURCE_KEYS = ["youtube", "bandcamp", "soundcloud", "twitch", "vimeo", "nico", "http", "local"];

const FILTER_KEYS = [
    "volume", "equalizer", "karaoke", "timescale", "tremolo",
    "vibrato", "distortion", "rotation", "channelMix", "lowPass",
];

/** True when a plugin in the list replaces Lavalink's built-in YouTube source. */
const hasYoutubePlugin = (plugins = []) =>
    plugins.some((p) => /youtube-plugin/i.test(String(p?.dependency || "")));

/**
 * Render the shared application.yml.
 * `settings.yamlOverride` (a non-empty string) is used verbatim — the escape
 * hatch for options this form does not model.
 */
const renderYaml = (settings) => {
    if (typeof settings?.yamlOverride === "string" && settings.yamlOverride.trim()) {
        return settings.yamlOverride.endsWith("\n") ? settings.yamlOverride : `${settings.yamlOverride}\n`;
    }

    const s = settings || {};
    const plugins = Array.isArray(s.plugins) ? s.plugins : [];
    const sources = s.sources || {};
    const filters = s.filters || {};

    // Lavalink refuses to start with both its built-in YouTube source and the
    // youtube plugin enabled. The plugin is the one that actually works, so the
    // built-in loses — silently fixing it here beats a node that boot-loops.
    const youtubeBuiltIn = hasYoutubePlugin(plugins) ? false : sources.youtube !== false;

    const lines = [];
    lines.push(HEADER, "");
    lines.push("server:");
    lines.push(`  port: ${parseInt(s.port, 10) || 2333}`);
    lines.push(`  address: ${q(s.address || "0.0.0.0")}`);
    lines.push("  http2:");
    lines.push("    enabled: false");
    lines.push("");
    lines.push("lavalink:");

    if (plugins.length) {
        lines.push("  plugins:");
        for (const p of plugins) {
            if (!p?.dependency) continue;
            lines.push(`    - dependency: ${q(p.dependency)}`);
            lines.push(`      repository: ${q(p.repository || "https://maven.lavalink.dev/releases")}`);
            lines.push(`      snapshot: ${p.snapshot === true}`);
        }
    }

    lines.push("  server:");
    lines.push(`    password: ${q(s.password)}`);
    lines.push("    sources:");
    for (const key of SOURCE_KEYS) {
        const value = key === "youtube" ? youtubeBuiltIn : sources[key] === true;
        lines.push(`      ${key}: ${value}`);
    }
    lines.push("    filters:");
    for (const key of FILTER_KEYS) {
        lines.push(`      ${key}: ${filters[key] !== false}`);
    }
    lines.push(`    bufferDurationMs: ${parseInt(s.bufferDurationMs, 10) || 400}`);
    lines.push(`    frameBufferDurationMs: ${parseInt(s.frameBufferDurationMs, 10) || 5000}`);
    lines.push(`    opusEncodingQuality: ${parseInt(s.opusEncodingQuality, 10) || 10}`);
    lines.push(`    resamplingQuality: ${s.resamplingQuality || "LOW"}`);
    lines.push(`    trackStuckThresholdMs: ${parseInt(s.trackStuckThresholdMs, 10) || 10000}`);
    lines.push("    useSeekGhosting: true");
    lines.push(`    youtubePlaylistLoadLimit: ${parseInt(s.youtubePlaylistLoadLimit, 10) || 6}`);
    lines.push(`    playerUpdateInterval: ${parseInt(s.playerUpdateInterval, 10) || 5}`);
    lines.push("    youtubeSearchEnabled: true");
    lines.push("    soundcloudSearchEnabled: true");
    lines.push("    gc-warnings: true");
    lines.push("");
    lines.push("metrics:");
    lines.push("  prometheus:");
    lines.push("    enabled: false");
    lines.push("    endpoint: /metrics");
    lines.push("");
    lines.push("logging:");
    lines.push("  file:");
    lines.push("    path: ./logs/");
    lines.push("  level:");
    lines.push("    root: INFO");
    lines.push("    lavalink: INFO");
    lines.push("  request:");
    lines.push("    enabled: true");
    lines.push("    includeClientInfo: true");
    lines.push("    includeHeaders: false");
    lines.push("    includeQueryString: true");
    lines.push("    includePayload: true");
    lines.push("    maxPayloadLength: 10000");
    lines.push("  logback:");
    lines.push("    rollingpolicy:");
    lines.push("      max-file-size: 100MB");
    lines.push("      max-history: 7");
    lines.push("");

    return lines.join("\n");
};

const sha256 = (text) => crypto.createHash("sha256").update(Buffer.from(text, "utf8")).digest("hex");

module.exports = { renderYaml, sha256, hasYoutubePlugin, SOURCE_KEYS, FILTER_KEYS };
