const { exec, spawn } = require("child_process");
const util = require("util");
const execAsync = util.promisify(exec);
const fs = require("fs");
const path = require("path");

// ─────────────────────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Execute a PM2 CLI command and return stdout.
 * --no-color strips ANSI codes from output.
 */
const runPM2 = async (args) => {
    const { stdout, stderr } = await execAsync(
        `env -u PORT pm2 ${args} --no-color`,
    );
    return stdout || stderr;
};

/**
 * Persist the current PM2 process list so it survives reboots.
 * Errors are silenced — a failed save should never break the caller.
 */
const pm2Save = async () => {
    try {
        await execAsync("pm2 save --no-color");
    } catch {
        // non-critical — log but don't throw
        console.warn("[PM2] pm2 save failed (non-critical)");
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Process Control
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Write a proxychains4 config file inside the bot's directory.
 * Returns the path to the generated config file.
 *
 * @param {string} botPath   - Bot working directory
 * @param {Object} proxyConf - { type, host, port, username, password }
 */
const writeProxyConfig = (botPath, proxyConf) => {
    const { type = "socks5", host, port, username, password } = proxyConf;
    const authLine =
        username && password ? `\n${type} ${host} ${port} ${username} ${password}` : `\n${type} ${host} ${port}`;
    const content = `# Generated by bot-panel — do not edit manually
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]${authLine}
`;
    const confPath = path.join(botPath, ".proxychains4.conf");
    fs.writeFileSync(confPath, content, "utf8");
    return confPath;
};

/**
 * Start a bot with PM2.
 * If the process already exists in PM2, it will be restarted instead.
 *
 * @param {string} pm2Name     - Unique PM2 name, e.g. "buyer123-mybot"
 * @param {string} botPath     - Absolute path to the bot's directory
 * @param {string} startCommand - Command to execute (e.g., "npm start", "java -jar ...")
 * @param {string|null} maxMemory - Memory limit e.g. "300M", "1G" (optional)
 * @param {Object|null} proxyConf - Proxy config { type, host, port, username, password } or null
 */
const startBot = async (
    pm2Name,
    botPath,
    startCommand = "npm start",
    maxMemory = null,
    proxyConf = null,
) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";

    // Check if process already exists in PM2 list
    const list = await getProcessList();
    const existing = list.find((p) => p.name === pm2Name);

    let result;
    if (existing) {
        // Already registered — delete and re-register so wrapper script is refreshed
        await runPM2(`delete "${pm2Name}"`);
    }

    // Determine actual command — prepend proxychains4 if proxy is configured
    let effectiveCmd = startCommand.trim();
    const isWindows = process.platform === "win32";

    if (proxyConf && !isWindows) {
        // Write per-bot proxychains4 config
        const confPath = writeProxyConfig(botPath, proxyConf);
        effectiveCmd = `proxychains4 -f "${confPath}" ${effectiveCmd}`;
        console.log(`[PM2] Proxy enabled for "${pm2Name}" via ${proxyConf.host}:${proxyConf.port}`);
    }

    const scriptName = isWindows ? ".noflex-start.bat" : ".noflex-start.sh";
    const scriptPath = `${botPath}/${scriptName}`;
    let interpreterFlag = "";

    // Simple script filename mode for backward compatibility
    if (
        !effectiveCmd.includes(" ") &&
        (effectiveCmd.endsWith(".js") ||
            effectiveCmd.endsWith(".ts") ||
            effectiveCmd.endsWith(".py") ||
            effectiveCmd.endsWith(".json"))
    ) {
        // Single file — run directly (no wrapper needed, proxy prefix already applied above)
        result = await runPM2(
            `start "${botPath}/${effectiveCmd}" --name "${pm2Name}" --cwd "${botPath}"${memFlag}`,
        );
    } else {
        // Complex command — generate a wrapper script
        const scriptContent = isWindows
            ? `@echo off\n${effectiveCmd}`
            : `#!/bin/bash\n${effectiveCmd}`;
        fs.writeFileSync(scriptPath, scriptContent);
        if (!isWindows) {
            try { fs.chmodSync(scriptPath, 0o755); } catch (e) {}
            interpreterFlag = " --interpreter bash";
        }

        result = await runPM2(
            `start "${scriptPath}" --name "${pm2Name}" --cwd "${botPath}"${memFlag}${interpreterFlag}`,
        );
    }

    await pm2Save();
    return result;
};

/**
 * Apply or remove a memory restart limit on an already-registered PM2 process.
 * Call this when the admin changes maxMemory on a running bot.
 *
 * @param {string} pm2Name  - PM2 process name
 * @param {string|null} maxMemory - New limit e.g. "512M" or null to remove
 */
const setMemoryLimit = async (pm2Name, maxMemory) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";
    const result = await runPM2(`restart "${pm2Name}"${memFlag}`);
    await pm2Save();
    return result;
};

/** Stop a running bot (keeps it in PM2 list) */
const stopBot = async (pm2Name) => {
    const result = await runPM2(`stop "${pm2Name}"`);
    await pm2Save();
    return result;
};

/** Restart a bot */
const restartBot = async (pm2Name) => {
    const result = await runPM2(`restart "${pm2Name}"`);
    await pm2Save();
    return result;
};

/**
 * Remove a bot from PM2 entirely.
 * Called on expiry or manual deletion. Errors are silenced (process may not exist).
 */
const deleteBot = async (pm2Name) => {
    try {
        const result = await runPM2(`delete "${pm2Name}"`);
        await pm2Save();
        return result;
    } catch {
        // Process doesn't exist in PM2 — that's fine
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Status & Info
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get the full PM2 process list as parsed JSON.
 * Returns an empty array if PM2 is not available or has no processes.
 */
const getProcessList = async () => {
    try {
        const { stdout } = await execAsync("pm2 jlist --no-color");
        return JSON.parse(stdout || "[]");
    } catch {
        return [];
    }
};

/**
 * Get live status info for a specific PM2 process.
 *
 * @returns {Object} { status, cpu, memory, restarts, uptime }
 */
const getBotStatus = async (pm2Name, cachedList = null) => {
    const list = cachedList || (await getProcessList());
    const proc = list.find((p) => p.name === pm2Name);

    if (!proc)
        return {
            status: "stopped",
            cpu: 0,
            memory: 0,
            restarts: 0,
            uptime: null,
        };

    return {
        status: proc.pm2_env.status, // 'online' | 'stopped' | 'errored' | 'launching'
        cpu: proc.monit?.cpu ?? 0,
        memory: proc.monit?.memory ?? 0,
        restarts: proc.pm2_env.restart_time ?? 0,
        uptime: proc.pm2_env.pm_uptime ?? null,
    };
};

// ─────────────────────────────────────────────────────────────────────────────
//  Logs
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch the last N lines of logs for a bot (snapshot, not streaming).
 *
 * @param {string} pm2Name
 * @param {number} lines - How many lines to return
 */
const getBotLogs = async (pm2Name, lines = 100) => {
    try {
        const { stdout } = await execAsync(
            `pm2 logs "${pm2Name}" --lines ${lines} --nostream --no-color`,
        );
        return stdout;
    } catch (err) {
        return err.message;
    }
};

/**
 * Spawn a `pm2 logs` process for live streaming.
 * Returns the ChildProcess — caller is responsible for killing it.
 *
 * @param {string} pm2Name
 * @param {number} lines - Initial history lines to show
 */
const streamBotLogs = (pm2Name, lines = 50) => {
    return spawn(
        "pm2",
        ["logs", pm2Name, "--lines", String(lines), "--raw", "--no-color"],
        {
            stdio: ["ignore", "pipe", "pipe"],
        },
    );
};

module.exports = {
    startBot,
    stopBot,
    restartBot,
    deleteBot,
    setMemoryLimit,
    getBotStatus,
    getBotLogs,
    streamBotLogs,
    getProcessList,
};
