const { exec, spawn } = require("child_process");
const util = require("util");
const execAsync = util.promisify(exec);
const fs = require("fs");
const path = require("path");

// ─────────────────────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Execute a PM2 CLI command and return stdout.
 * --no-color strips ANSI codes from output.
 */
const runPM2 = async (args) => {
    const { stdout, stderr } = await execAsync(
        `env -u PORT pm2 ${args} --no-color`,
    );
    return stdout || stderr;
};

/**
 * Persist the current PM2 process list so it survives reboots.
 * Errors are silenced — a failed save should never break the caller.
 */
const pm2Save = async () => {
    try {
        await execAsync("pm2 save --no-color");
    } catch {
        // non-critical — log but don't throw
        console.warn("[PM2] pm2 save failed (non-critical)");
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Process Control
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Write a proxychains4 config file inside the bot's directory.
 * Returns the path to the generated config file.
 *
 * @param {string} botPath   - Bot working directory
 * @param {Object} proxyConf - { type, host, port, username, password }
 */
const writeProxyConfig = (botPath, proxyConf) => {
    const { type = "socks5", host, port, username, password } = proxyConf;
    const authLine =
        username && password ? `\n${type} ${host} ${port} ${username} ${password}` : `\n${type} ${host} ${port}`;
    const content = `# Generated by bot-panel — do not edit manually
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]${authLine}
`;
    const confPath = path.join(botPath, ".proxychains4.conf");
    fs.writeFileSync(confPath, content, "utf8");
    return confPath;
};

/**
 * Start a bot with PM2.
 * If the process already exists in PM2, it will be restarted instead.
 *
 * @param {string} pm2Name     - Unique PM2 name, e.g. "buyer123-mybot"
 * @param {string} botPath     - Absolute path to the bot's directory
 * @param {string} startCommand - Command to execute (e.g., "npm start", "java -jar ...")
 * @param {string|null} maxMemory - Memory limit e.g. "300M", "1G" (optional)
 * @param {Object|null} proxyConf - Proxy config { type, host, port, username, password } or null
 */
const startBot = async (
    pm2Name,
    botPath,
    startCommand = "npm start",
    maxMemory = null,
    proxyConf = null,
) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";

    // Check if process already exists in PM2 list
    const list = await getProcessList();
    const existing = list.find((p) => p.name === pm2Name);

    let result;
    if (existing) {
        // Already registered — delete and re-register so wrapper script is refreshed
        await runPM2(`delete "${pm2Name}"`);
    }

    // ── Step 1: Resolve single-file scripts to their explicit runtime ──────────
    // PM2 knows to call `node index.js` when given a bare .js file directly,
    // but a shell wrapper (needed for proxychains4) does NOT — it tries to exec
    // the file as a binary and fails. Convert bare filenames to full commands.
    let effectiveCmd = startCommand.trim();
    const isWindows = process.platform === "win32";

    const isBareFile = (cmd) =>
        !cmd.includes(" ") &&
        (cmd.endsWith(".js") || cmd.endsWith(".ts") || cmd.endsWith(".py") || cmd.endsWith(".json"));

    if (isBareFile(effectiveCmd)) {
        if (effectiveCmd.endsWith(".js")) {
            effectiveCmd = `node ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".ts")) {
            effectiveCmd = `npx ts-node ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".py")) {
            effectiveCmd = `python3 ${effectiveCmd}`;
        } else if (effectiveCmd.endsWith(".json")) {
            // PM2 ecosystem file — call pm2 itself (proxy wraps the outer process)
            effectiveCmd = `pm2 start ${effectiveCmd}`;
        }
        console.log(`[PM2] Resolved bare file to: ${effectiveCmd}`);
    }

    // ── Step 2: Prepend proxychains4 if proxy is active ────────────────────────
    if (proxyConf && !isWindows) {
        const confPath = writeProxyConfig(botPath, proxyConf);
        effectiveCmd = `proxychains4 -f "${confPath}" ${effectiveCmd}`;
        console.log(`[PM2] Proxy enabled for "${pm2Name}" via ${proxyConf.host}:${proxyConf.port}`);
    }

    // ── Step 3: Always run via wrapper script so the shell resolves the command ─
    const scriptName = isWindows ? ".noflex-start.bat" : ".noflex-start.sh";
    const scriptPath = `${botPath}/${scriptName}`;
    let interpreterFlag = "";

    // NOTE: must use actual newline character, NOT a literal backslash-n.
    const NL = "\n";
    // exec only works for simple commands — shell operators (&& ; | ||) require bash to run the full line
    const hasShellOps = /[;&|]/.test(effectiveCmd);
    const scriptContent = isWindows
        ? `@echo off${NL}${effectiveCmd}`
        : `#!/bin/bash${NL}${hasShellOps ? effectiveCmd : `exec ${effectiveCmd}`}`;
    fs.writeFileSync(scriptPath, scriptContent, "utf8");
    if (!isWindows) {
        try { fs.chmodSync(scriptPath, 0o755); } catch (e) {}
        interpreterFlag = " --interpreter bash";
    }

    console.log(`[PM2] Wrapper script for "${pm2Name}": ${scriptPath}`);
    console.log(`[PM2] Effective command: ${effectiveCmd}`);

    result = await runPM2(
        `start "${scriptPath}" --name "${pm2Name}" --cwd "${botPath}"${memFlag}${interpreterFlag}`,
    );

    await pm2Save();
    return result;
};

/**
 * Apply or remove a memory restart limit on an already-registered PM2 process.
 * Call this when the admin changes maxMemory on a running bot.
 *
 * @param {string} pm2Name  - PM2 process name
 * @param {string|null} maxMemory - New limit e.g. "512M" or null to remove
 */
const setMemoryLimit = async (pm2Name, maxMemory) => {
    const memFlag = maxMemory ? ` --max-memory-restart ${maxMemory}` : "";
    const result = await runPM2(`restart "${pm2Name}"${memFlag}`);
    await pm2Save();
    return result;
};

/**
 * Start a static website using http-server via PM2.
 * Serves the given distFolder on the given port — no nginx needed.
 *
 * @param {string} pm2Name    - Unique PM2 name
 * @param {string} distFolder - Absolute path to the static files directory
 * @param {number} port       - TCP port to listen on
 */
const startHttpServer = async (pm2Name, distFolder, port) => {
    const list = await getProcessList();
    const existing = list.find((p) => p.name === pm2Name);
    if (existing) {
        await runPM2(`delete "${pm2Name}"`);
    }

    // Prefer the local binary shipped with the panel; fall back to global
    const localBin = path.resolve(__dirname, "../../node_modules/.bin/http-server");
    const bin = fs.existsSync(localBin) ? localBin : "http-server";

    // Write a minimal shell wrapper so PM2 manages it like any other process
    const scriptPath = `/tmp/panel-site-${pm2Name}.sh`;
    fs.writeFileSync(
        scriptPath,
        `#!/bin/bash\nexec "${bin}" "${distFolder}" -p ${port} -a 0.0.0.0 --silent\n`,
        "utf8",
    );
    fs.chmodSync(scriptPath, 0o755);

    const result = await runPM2(
        `start "${scriptPath}" --name "${pm2Name}" --interpreter bash`,
    );
    await pm2Save();
    return result;
};

/** Stop a running bot (keeps it in PM2 list) */
const stopBot = async (pm2Name) => {
    const result = await runPM2(`stop "${pm2Name}"`);
    await pm2Save();
    return result;
};

/** Restart a bot */
const restartBot = async (pm2Name) => {
    const result = await runPM2(`restart "${pm2Name}"`);
    await pm2Save();
    return result;
};

/**
 * Remove a bot from PM2 entirely.
 * Called on expiry or manual deletion. Errors are silenced (process may not exist).
 */
const deleteBot = async (pm2Name) => {
    try {
        const result = await runPM2(`delete "${pm2Name}"`);
        await pm2Save();
        return result;
    } catch {
        // Process doesn't exist in PM2 — that's fine
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  Status & Info
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get the full PM2 process list as parsed JSON.
 * Returns an empty array if PM2 is not available or has no processes.
 */
const getProcessList = async () => {
    try {
        const { stdout } = await execAsync("pm2 jlist --no-color");
        return JSON.parse(stdout || "[]");
    } catch {
        return [];
    }
};

/**
 * Get live status info for a specific PM2 process.
 *
 * @returns {Object} { status, cpu, memory, restarts, uptime }
 */
const getBotStatus = async (pm2Name, cachedList = null) => {
    const list = cachedList || (await getProcessList());
    const proc = list.find((p) => p.name === pm2Name);

    if (!proc)
        return {
            status: "stopped",
            cpu: 0,
            memory: 0,
            restarts: 0,
            uptime: null,
        };

    return {
        status: proc.pm2_env.status, // 'online' | 'stopped' | 'errored' | 'launching'
        cpu: proc.monit?.cpu ?? 0,
        memory: proc.monit?.memory ?? 0,
        restarts: proc.pm2_env.restart_time ?? 0,
        uptime: proc.pm2_env.pm_uptime ?? null,
    };
};

// ─────────────────────────────────────────────────────────────────────────────
//  Logs
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch the last N lines of logs for a bot (snapshot, not streaming).
 *
 * @param {string} pm2Name
 * @param {number} lines - How many lines to return
 */
const getBotLogs = async (pm2Name, lines = 100) => {
    try {
        const { stdout } = await execAsync(
            `pm2 logs "${pm2Name}" --lines ${lines} --nostream --no-color`,
        );
        return stdout;
    } catch (err) {
        return err.message;
    }
};

/**
 * Spawn a `pm2 logs` process for live streaming.
 * Returns the ChildProcess — caller is responsible for killing it.
 *
 * @param {string} pm2Name
 * @param {number} lines - Initial history lines to show
 */
const streamBotLogs = (pm2Name, lines = 50) => {
    return spawn(
        "pm2",
        ["logs", pm2Name, "--lines", String(lines), "--raw", "--no-color"],
        {
            stdio: ["ignore", "pipe", "pipe"],
        },
    );
};

/**
 * Flush all PM2 logs.
 */
const flushLogs = async () => {
    try {
        await runPM2("flush");
    } catch (err) {
        console.error("[PM2] Failed to flush logs", err);
    }
};

/**
 * Flush logs for a specific PM2 process by name.
 */
const flushBotLogs = async (pm2Name) => {
    await execAsync(`pm2 flush "${pm2Name}"`);
};

module.exports = {
    startBot,
    startHttpServer,
    stopBot,
    restartBot,
    deleteBot,
    setMemoryLimit,
    getBotStatus,
    getBotLogs,
    streamBotLogs,
    getProcessList,
    flushLogs,
    flushBotLogs,
};
