#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  bot-panel agent — remove what setup-agent.sh installed for one user
#
#  Usage:  sudo bash uninstall-agent.sh <USER>
#          (the user the agent ran as: "root", or e.g. "khaidev")
#
#  Remove the node on the panel first (its page → Remove), so the other nodes
#  drop it from the WireGuard mesh.
#
#  What it removes — only what carries bot-panel's marks:
#    - panel-agent and lavalink from that user's PM2 (and PM2 itself for that
#      user, with its boot service, when nothing else is left in it)
#    - wg0, if /etc/wireguard/wg0.conf was written by bot-panel
#    - the UFW rules for the agent port and WireGuard (51820/udp)
#    - SSH keys the panel copied over (those with a "# GitHub key:" entry in
#      ~/.ssh/config) and their config entries
#    - ~/panel, ~/lavalink, ~/.panel-node, and ~/bots / ~/sites when empty
#    - /etc/sudoers.d/bot-panel-agent-<user>
#
#  Kept: installed packages (Node, PM2, nginx, WireGuard, Java — a new setup
#  needs them again), the SSH rule and UFW itself, git's global user.name/email.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

TARGET_USER="${1:?Usage: sudo bash uninstall-agent.sh <USER>   (the user the agent ran as)}"
if [ "$(id -u)" != "0" ]; then
    echo "Run it as root: sudo bash $0 $TARGET_USER" >&2
    exit 1
fi
H=$(getent passwd "$TARGET_USER" | cut -d: -f6 || true)
if [ -z "$H" ]; then
    echo "No such user: $TARGET_USER" >&2
    exit 1
fi
DIR="$H/panel"

as_user() {
    if [ "$TARGET_USER" = "root" ]; then "$@"; else sudo -u "$TARGET_USER" -H "$@"; fi
}
say() { echo "[uninstall] $*"; }

# Never on the machine that runs the panel: its checkout and SSH keys are the
# panel's own.
if as_user pm2 describe bot-panel >/dev/null 2>&1 || grep -qs '^PANEL_DIR=.\+' "$DIR/agent/.env"; then
    echo "This looks like the node that runs the panel (bot-panel in PM2, or PANEL_DIR set) — not touching it." >&2
    echo "Move the panel away first (Panel Settings → Move Panel)." >&2
    exit 1
fi

AGENT_PORT=$(grep -s '^AGENT_PORT=' "$DIR/agent/.env" | cut -d= -f2)
AGENT_PORT="${AGENT_PORT:-4200}"

echo "──────────────────────────────────────────────"
echo " bot-panel agent uninstall for $TARGET_USER ($H), agent port $AGENT_PORT"
echo "──────────────────────────────────────────────"

# 1. PM2 ──────────────────────────────────────────────────────────────────────
if command -v pm2 >/dev/null 2>&1; then
    for p in panel-agent lavalink; do
        if as_user pm2 describe "$p" >/dev/null 2>&1; then
            as_user pm2 delete "$p" >/dev/null && say "PM2: removed $p"
        fi
    done
    as_user pm2 save --force >/dev/null 2>&1
    if [ "$(as_user pm2 jlist 2>/dev/null)" = "[]" ]; then
        if [ -f "/etc/systemd/system/pm2-$TARGET_USER.service" ]; then
            pm2 unstartup systemd -u "$TARGET_USER" --hp "$H" >/dev/null 2>&1 && say "PM2: boot service pm2-$TARGET_USER removed"
        fi
        as_user pm2 kill >/dev/null 2>&1
        rm -rf "$H/.pm2" && say "PM2: nothing else ran for $TARGET_USER — removed $H/.pm2"
    else
        say "PM2: $TARGET_USER still runs other processes — PM2 and its boot service kept"
    fi
fi

# 2. WireGuard ────────────────────────────────────────────────────────────────
if head -1 /etc/wireguard/wg0.conf 2>/dev/null | grep -q "Generated by bot-panel"; then
    wg-quick down wg0 >/dev/null 2>&1
    systemctl disable wg-quick@wg0 >/dev/null 2>&1
    rm -f /etc/wireguard/wg0.conf
    say "WireGuard: wg0 down, disabled, config removed"
fi

# 3. Firewall ─────────────────────────────────────────────────────────────────
# By number, highest first, so the numbers of the rest do not shift.
if command -v ufw >/dev/null 2>&1; then
    NUMS=$(ufw status numbered 2>/dev/null | grep -E "(^|[^0-9])($AGENT_PORT/tcp|51820/udp)([^0-9]|$)" | sed -n 's/^\[ *\([0-9]\+\)\].*/\1/p' | sort -rn)
    for n in $NUMS; do ufw --force delete "$n" >/dev/null; done
    [ -n "$NUMS" ] && say "UFW: removed the rules for $AGENT_PORT/tcp and 51820/udp"
fi

# 4. SSH keys the panel copied ────────────────────────────────────────────────
CFG="$H/.ssh/config"
if [ -f "$CFG" ]; then
    for name in $(sed -n 's/^# GitHub key: \([A-Za-z0-9_.-]\+\)$/\1/p' "$CFG"); do
        rm -f "$H/.ssh/$name" "$H/.ssh/$name.pub"
        # The entry the agent wrote: the marker, "Host github.com-<name>" and its
        # indented lines. As the user, so the rewritten file stays theirs.
        as_user sed -i "/^# GitHub key: ${name//./\\.}\$/,/^    IdentitiesOnly yes\$/d" "$CFG"
        say "SSH: removed key $name"
    done
fi

# 5. Files ────────────────────────────────────────────────────────────────────
if [ -f "$DIR/agent/index.js" ]; then
    rm -rf "$DIR" && say "Removed $DIR"
elif [ -e "$DIR" ]; then
    say "$DIR is not a bot-panel checkout — left alone"
fi
for d in "$H/lavalink" "$H/.panel-node"; do
    [ -e "$d" ] && rm -rf "$d" && say "Removed $d"
done
for d in "$H/bots" "$H/sites"; do
    if [ -d "$d" ]; then
        if rmdir "$d" 2>/dev/null; then say "Removed $d (empty)"; else say "$d is not empty — kept"; fi
    fi
done
SUDOERS="/etc/sudoers.d/bot-panel-agent-$(printf %s "$TARGET_USER" | tr -c 'a-zA-Z0-9_-' '_')"
[ -f "$SUDOERS" ] && rm -f "$SUDOERS" && say "Removed $SUDOERS"

echo "──────────────────────────────────────────────"
echo " Done. Still here on purpose: installed packages, UFW with its SSH rule."
echo " UFW is $(ufw status 2>/dev/null | head -1 | sed 's/Status: //'). If it was off before the setup: sudo ufw disable"
echo "──────────────────────────────────────────────"
